### ISSUE TITLE
Something wrong in configtx.yaml

### ISSUE THREAD

**Issue by learnergo** [jcs47/hyperledger-bftsmart#30]
I use the yaml provided from you :
```
https://raw.githubusercontent.com/wiki/bft-smart/fabric-orderingservice/configuration-material/v1.2/configtx.yaml
```

I find two mistakes.
First ,
```
- &Frontends
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Frontends

        # ID to load the MSP definition as
        ID: FrontendsMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/frontend.bft/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('FrontendsMSP.member')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('FrontendsMSP.admin', 'FrontendsMSP.peer', 'FrontendsMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('FrontendsMSP.member')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('FrontendsMSP.admin', 'FrontendsMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Frontends.admin')"

```

The last line should be 
```
 Rule: "OR('FrontendsMSP.admin')"
```

Second,
```
Edit the GENESIS and MSPID parameters at the ./<TYPE>__material/config/node.config file. GENESIS should be the path to the genesis block within the container. MSPID should be set to "OrderingNodes" at the ordering nodes, and "Frontends" at the frontends.
```

The MSPID should be the same with which defined in configtx.yaml
